
name: Cypress Tests in chrome

on: 
  push:
     branches: 
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x' 

    - name: Install dependencies
      run: npm install

    - name: Start the application
      run: npm run dev &
      env:
        CI: true

    - name: Wait for application to be ready
      run: npx wait-on http://localhost:5173

    - name: Run Cypress tests
      run: npm test

    - name: Upload Cypress test results
      uses: actions/upload-artifact@v2
      with:
        name: cypress-test-results
        path: cypress/reports