
name: Cypress Tests in chrome

on: 
  push:
     branches: 
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x' 

    - name: Install dependencies
      run: npm install

    - name: Set Workflow Run Name to "Cypress Tests Started"
      uses: actions/github-script@v6
      with:
        script: |
          const { context } = require('@actions/github');
          const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
          await octokit.rest.actions.updateWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId,
            name: 'Cypress Tests Started'
          });

    - name: Start the application
      run: npm run dev &
      env:
        CI: true

   

    - name: Run Cypress tests
      run: npx cypress run --browser chrome
      
      
    - name: Set Workflow Run Name to "Cypress Tests Succeeded"
      if: success()
      uses: actions/github-script@v6
      with:
        script: |
          const { context } = require('@actions/github');
          const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
          await octokit.rest.actions.updateWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId,
            name: 'Cypress Tests Succeeded'
          });

    - name: Upload Cypress test results
      uses: actions/upload-artifact@v3
      with:
        name: cypress-test-results
        path: cypress/reports